services:
  app:
    container_name: ls-app
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - postgres
  
  postgres:
    container_name: ls-postgres
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432