services:
  app:
    container_name: ls-app
    build: .
    ports: 
      - "3000:3000"
  
  postgres:
    container_name: ls-postgres
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432