services:
  app:
    container_name: ls-app
    build: .
    ports: 
      - "3000:3000"
  
  mongo:
    container_name: ls-mongo
    image: mongo:noble
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017

  mongo-express:
    container_name: ls-mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:mongo@mongo:27017/
      - ME_CONFIG_BASICAUTH=false