services:
  app:
    container_name: ls-app-prod
    image: nicolasgandrade/api-link-sharing:latest
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - CLIENT_ORIGIN_URL=${CLIENT_ORIGIN_URL}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_ISSUER=${AUTH0_ISSUER}
      - AUTH0_TOKEN_ALG=${AUTH0_TOKEN_ALG}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres

  postgres:
    container_name: ls-postgres-prod
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgAdmin:
    container_name: ls-pgAdmin
    image: dpage/pgadmin4
    ports:
      - '1532:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
